[buildPlans.Brosevka]
family = "Brosevka"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Brosevka.variants]
  inherits = "ss08"

    [buildPlans.Brosevka.variants.design]
    capital-n = "standard-serifless"
    capital-q = "crossing-curly-tailed"
    capital-x = "straight-serifless"
    f = "flat-hook-serifless"
    g = "single-storey-flat-hook-serifless"
    l = "serifed-flat-tailed"
    y = "straight-turn-serifless"
    zero = "slashed"
    four = "semi-open-non-crossing-serifless"
    eight = "two-circles"
    asterisk = "penta-high"
    paren = "normal"
    brace = "curly"
    dollar = "through"
    percent = "rings-continuous-slash"
    bar = "force-upright"
    question = "corner"
    lig-ltgteq = "flat"

    [buildPlans.Brosevka.variants.italic]
    f = "flat-hook-tailed"
    g = "double-storey-open"
    l = "serifed-diagonal-tailed"
    y = "cursive-serifless"

[buildPlans.Brosevka.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.Brosevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Brosevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
