name: Build and Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:fontforge/fontforge
          sudo apt-get install -y --no-install-recommends fontforge zip ttfautohint build-essential
          ./tools/setup.sh

      - name: Build fonts
        run: |
          ./tools/build-parallel.sh

      - name: Upload release files
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: releases/*

