name: Build and Publish
on:
  release:
    types: [published]
jobs:
  build-font:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - && \
          sudo apt-get install -y nodejs
          sudo add-apt-repository -y ppa:fontforge/fontforge
          sudo apt-get install -y fontforge zip ttfautohint
          ./tools/setup.sh
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Build fonts
        run: ./tools/build.sh
      - name: Upload release files
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: releases/*

