name: PR Font Build Validation

on: [pull_request]

jobs:
  build:
    if: github.repository == 'mbromell/brosevka'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ttfautohint

      - name: Build Font
        run: |
          npm install
          npm run build -- ttf::Brosevka
